routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('services', 'ServiceController');
Route::get('services/subcategory/{id}',array('as'=>'subcategory','uses'=>'ServiceController@SubcategoryAjax'));

app/Categories.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;


class Categories extends Model
{
    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $table = 'categories';

    protected $fillable = [
        'name', 'status'
    ];

    public function services()
	{
	return $this->hasMany('App\Services','id','category_id');
	}
	
	public function subCategories()
	{
	return $this->hasMany('App\SubCategories','id','category_id');
	}

}

app/Services.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;


class Services extends Model
{
    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $table = 'services';

    protected $fillable = [
        'name', 'description','category_id','subcategory_id','status','activation_start_date','activation_end_date'
    ];

    public function categories()
    {
        return $this->belongsTo('App\Categories','category_id','id');
    }

    public function subCategories()
	{
	   return $this->belongsTo('App\SubCategories','subcategory_id','id');
	}
}

app/SubCategories.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;


class SubCategories extends Model
{
    /**
     * The attributes that are mass assignable.
     *  
     * @var array
     */
    protected $table = 'sub_categories';

    protected $fillable = [
        'name', 'status','category_id'
    ];

    public function services()
    {
    return $this->hasMany('App\Services','subcategory_id','id');
    }
    
    public function categories()
    {
    return $this->belongsTo('App\Categories','id','category_id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ServiceController.php
<?php


namespace App\Http\Controllers;


use App\Services;
use App\Categories;
use App\SubCategories;
use Illuminate\Http\Request;
//use Datatables;
use Auth;

class ServiceController extends Controller
{ 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
                 
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //$services = Services::latest()->paginate(5);
        
        $services = Services::with('categories','subCategories')->where('status',1);
        if (isset ( $request->name )) {
            $services->where ( 'name', 'LIKE', '%' . $request->name . '%' );
        }
        if (isset ( $request->category_id )) {
            $services->where ( 'category_id',$request->category_id );
        }
        if (isset ( $request->subcategory_id )) {
            $services->where ( 'subcategory_id',$request->subcategory_id );
        }

        if (isset($request->activation_start) && !empty ( $request->activation_start ) && !empty ( $request->activation_end ) && isset($request->activation_end) ) {
            
            $startDate=$request->activation_start;
            $endDate=$request->activation_end;
            $services->where(function($q) use($startDate, $endDate) {
                $q->whereBetween('activation_start_date',[$startDate,$endDate]);
                $q->orWhereBetween('activation_end_date',[$startDate,$endDate]);
            });
        }

        $categories = Categories::select('id','name')->get()->pluck('name','id');
        $services=$services->paginate(5);
        
        return view('services.index',compact('services','categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $categories = Categories::select('id','name')->get()->pluck('name','id');
        return view('services.create',compact('categories'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        request()->validate([
            'title' => 'required',
            'description' => 'required',
            'category_id' => 'required',
            'subcategory_id' => 'required',
            'activation_start' => 'required',
            'activation_end' => 'required'
        ]);

        $input=$request->all();
        
        Services::create($input);


        return redirect()->route('services.index')
                        ->with('success','Service created successfully.');
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Services $service)
    {
        return view('services.show',compact('service'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Services $service)
    {
        return view('services.edit',compact('service'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Services $service)
    {
         request()->validate([
            'title' => 'required',
            'description' => 'required',
            'category_id' => 'required',
            'subcategory_id' => 'required',
            'activation_start' => 'required',
            'activation_end' => 'required'
        ]);


        $service->update($request->all());


        return redirect()->route('services.index')
                        ->with('success','service updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Services $service)
    {
        $service->delete();


        return redirect()->route('services.index')
                        ->with('success','service deleted successfully');
    }

    public function SubcategoryAjax($id)
    {
        $sub_categories = SubCategories::where("category_id",$id)->get()->pluck('name','id');
        return json_encode($sub_categories);
    }
}

resources/views/layouts/app.blade.php
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Scripts -->
    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <!-- Styles -->
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script> 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"></script> 
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  

<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet">   
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto"></ul>


                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                            <li><a class="nav-link" href="{{ route('services.index') }}">Manage Services</a></li>
                            
                    </ul>
                </div>
            </div>
        </nav>


        <main class="py-4">
            <div class="container">
            @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/layouts/app_2.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/services/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Services</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('services.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('services.store') }}" method="POST">
        
        <input type="hidden" name="_method" value="PUT">
        {{ csrf_field() }}
        <div class="row">
		    <div class="col-sm-4">
		        <div class="form-group">
		            <strong>Title:</strong>
		            <input type="text" name="name" class="form-control" placeholder="Title" required>
		        </div>
		    </div>
		    <div class="col-sm-4">
		        <div class="form-group">
		            <strong>description:</strong>
		            <textarea class="form-control" style="height:150px" name="description" placeholder="Description"></textarea>
		        </div>
		    </div>
            <div class="col-sm-4">
            <div class="form-group">
                <label for="title">Select Category:</label>
                <select name="category_id" class="form-control" style="width:350px" required>
                    <option value="">--- Select Category ---</option>
                    @foreach ($categories as $key => $value)
                        <option value="{{ $key }}">{{ $value }}</option>
                    @endforeach
                </select>
            </div>
            </div>
            <div class="col-sm-4">
            <div class="form-group">
                <select name="subcategory_id" class="form-control" style="width:350px" required>
                </select>
            </div>
            </div>
        </div>
        <div class="row">    
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="title">Select start date:</label>
                    <div class='input-group date' id='datetimepicker3'>
                        <input type='text' autocomplete="off" class="form-control datepicker" name="activation_start" id="datepicker_start" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="title">Select end date:</label>
                        <input type='text' autocomplete="off" class="form-control datepicker" name="activation_end" id="datepicker_end" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                </div>
            </div>
		</div>
        <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
            </div>
		


    </form>
    
    <script type="text/javascript">
    $(document).ready(function() {
        $('select[name="category_id"]').on('change', function() {

            var categoryID = $(this).val();
            if(categoryID) {
                $.ajax({
                    url: 'subcategory/'+categoryID,
                    type: "GET",
                    dataType: "json",
                    success:function(data) {

                        
                        $('select[name="subcategory_id"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="subcategory_id"]').append('<option value="'+ key +'">'+ value +'</option>');
                        });


                    }
                });
            }else{
                $('select[name="subcategory_id"]').empty();
            }
        });
    });
    $(function () {
            $("#datepicker_start").datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true });
        });
    $(function () {
            $("#datepicker_end").datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true });
        });
    </script>


@endsection

resources/views/services/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Services</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('services.create') }}"> Create New Service</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <br>
    <form action="{{ url('/services') }}" method="GET">
      <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <input type="text" name="name" placeholder="Search string"> 
                </div>
            </div>

        <div class="col-sm-4">
        <div class="form-group">
        <select name="category_id" class="form-control" style="width:350px">
            <option value="">--- Select Category ---</option>
            @foreach ($categories as $key => $value)
                <option value="{{ $key }}">{{ $value }}</option>
            @endforeach
        </select>
        </div>
        </div>
        
        <div class="col-sm-4">
        <div class="form-group">
            <select name="subcategory_id" class="form-control" style="width:350px">
            </select>
        </div>
        </div>
    </div>
    <div class="row">
        
        <div class="col-sm-4">
            <div class="form-group">
            <label for="title">Start Date:</label>
            <input autocomplete="off" type='text' class="form-control datepicker" name="activation_start" id="datepicker_start" />
            </div>
        </div>                            

        <div class="col-sm-4">
            <div class="form-group">
            <label for="title">End Date:</label>
            <input autocomplete="off" type='text' class="form-control datepicker" name="activation_end" id="datepicker_end" />
            </div>
        </div>                
    
    </div>
                
    
    <input  type="submit" name="submit" value="Search"> 
    </form>
    <table class="table table-bordered" style="border: 1">
        <tr>
            <th>No</th>
            <th>Title</th>
            <th>Description</th>
            <th>Category</th>
            <th>Sub category</th>
        </tr>

	    @foreach ($services as $service)
        
	    <tr>
	        <td>{{ ++$i }}</td>
	        <td>{{ $service->name }}</td>
	        <td>{{ $service->description }}</td>
            <td>{{ $service['categories']['name'] }}</td>
            <td>{{ $service['subcategories']['name'] }}</td>
	    </tr>
	    @endforeach
           {{ $services->links() }}
 
    </table>

    <script type="text/javascript">
    $(document).ready(function() {
            $('select[name="category_id"]').on('change', function() {

                var categoryID = $(this).val();
                if(categoryID) {
                    $.ajax({
                        url: 'services/subcategory/'+categoryID,
                        type: "GET",
                        dataType: "json",
                        success:function(data) {

                            
                            $('select[name="subcategory_id"]').empty();
                            $.each(data, function(key, value) {
                                $('select[name="subcategory_id"]').append('<option value="'+ key +'">'+ value +'</option>');
                            });


                        }
                    });
                }else{
                    $('select[name="subcategory_id"]').empty();
                }
            });
        });
       
    $(function () {
            $("#datepicker_start").datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true });
        });
    $(function () {
            $("#datepicker_end").datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true });
        });  
    
    </script>

@endsection